import { useRef, useCallback } from "react";

const SECTIONS = [
  { id: "harm", label: "Harm Scores", sources: [
    { name: "Nutt, King & Phillips — \"Drug harms in the UK\" (The Lancet, 2010)", url: "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(10)61462-6/fulltext", type: "Peer-reviewed", desc: "Harm scores for 14 of our substances come directly from this landmark MCDA. Four more (fentanyl, nitrous, DMT, poppers) now have MCDA scores from subsequent studies (Broman 2025, Ferreira 2022). The remaining substances (tramadol, kratom, DXM, 2C-x, PCP, mescaline, caffeine) are DoseGuide estimates marked with dashed bars. Note: nicotine is scored as 'tobacco' (26) — includes smoking harms, not nicotine alone." },
    { name: "Broman et al. — \"US drug policy does not align with experts' rankings\" (Harm Reduction Journal, 2025)", url: "https://doi.org/10.1186/s12954-025-01390-x", type: "Peer-reviewed", desc: "US expert MCDA scoring 19 drugs. Fentanyl scored highest at 90/100. Also scored DMT/ayahuasca (5), providing the first MCDA data for these substances. Used for our fentanyl and DMT harm scores." },
    { name: "Ferreira et al. — \"Drug harms: an international Delphi study\" (Drug Science, Policy and Law, 2022)", url: "https://doi.org/10.1177/20503245221127301", type: "Peer-reviewed", desc: "International Delphi MCDA study scoring additional substances not in Nutt 2010, including nitrous oxide (6/100) and poppers (5/100). Used for our nitrous and poppers harm scores." },
  ]},
  { id: "interactions", label: "Interactions", sources: [
    { name: "TripSit", url: "https://tripsit.me", type: "Community", desc: "The base drug combination chart is derived from TripSit v4.0. DoseGuide has corrected several ratings using peer-reviewed data: cocaine+opioids upgraded to 'Dangerous' (CDC SUDORS 2023: 47% of overdose deaths involve both), stimulant+opioid combos upgraded (unmasking mechanism), MDMA+SSRIs changed to 'Decrease' (Liechti 2000), and kratom interactions added (Olsen 2019).", link2: "https://wiki.tripsit.me/wiki/Drug_combinations", link2label: "Drug Combinations Wiki" },
    { name: "CDC SUDORS — State Unintentional Drug Overdose Reporting System", url: "https://www.cdc.gov/overdose-prevention/data-research/facts-stats/", type: "Government", desc: "47% of all drug overdose deaths in 2023 involved both opioids and stimulants. 79% of cocaine-involved deaths co-involved opioids. This data drove our upgrade of cocaine+opioids from 'Caution' to 'Dangerous' — a correction from the TripSit base data." },
    { name: "Liechti et al. — MDMA pharmacology studies (Neuropsychopharmacology, 2000 & Pharmacology, 2006)", url: "https://doi.org/10.1016/S0893-133X(99)00148-7", type: "Peer-reviewed", desc: "Liechti 2000: citalopram attenuated 30-80% of MDMA's subjective effects — SSRIs block MDMA rather than creating dangerous synergy. Liechti 2006: reviewed GHB+MDMA co-use, finding that stimulants do NOT protect against GHB overdose due to temporal mismatch in duration." },
    { name: "Boyer & Shannon — \"The serotonin syndrome\" (NEJM, 2005)", url: "https://doi.org/10.1056/NEJMra041867", type: "Peer-reviewed", desc: "Definitive review establishing that serotonin syndrome risk is highest when drugs affect serotonin through different mechanisms (reuptake inhibition + MAO inhibition + direct release). Used for mechanism explanations across serotonergic combinations." },
    { name: "Olsen et al. — Kratom-associated overdose deaths (MMWR, 2019)", url: "https://doi.org/10.15585/mmwr.mm6814a2", type: "Government", desc: "CDC surveillance of 152 kratom-positive overdose deaths. Only 4.6% had kratom as sole substance. 65% involved fentanyl, 33% heroin, 22% benzodiazepines. Used for kratom interaction ratings." },
    { name: "van Amsterdam et al. — Cocaethylene review (J Clinical Medicine, 2024)", url: "https://doi.org/10.3390/jcm13051475", type: "Peer-reviewed", desc: "Cocaethylene (formed from cocaine + alcohol in the liver) carries an 18-25x increase in sudden death risk vs. cocaine alone. Used for cocaine+alcohol mechanism explanation." },
    { name: "Kariisa et al. — Xylazine-involved overdose deaths (MMWR, 2023)", url: "https://doi.org/10.15585/mmwr.mm7226a4", type: "Government", desc: "Xylazine-involved deaths increased nearly 20-fold from 2015 to 2020. Philadelphia saw xylazine in up to 95% of fentanyl cases at peak. Xylazine and fentanyl suppress breathing through different mechanisms — naloxone alone is insufficient." },
    { name: "Nayak et al. — \"Classic psychedelic coadministration with lithium\" (J Psychopharmacology, 2021)", url: "https://doi.org/10.1177/0269881121991554", type: "Peer-reviewed", desc: "Retrospective analysis of 80 online experience reports of lithium + psychedelic use. 47% involved seizures and 39% required emergency medical attention. Used for our lithium warning on all psychedelic substance pages. Lamotrigine did not carry this risk." },
    { name: "FDA Drug Safety Communication — Gabapentin/Pregabalin Respiratory Depression (2019)", url: "https://www.fda.gov/safety/medical-product-safety-information/neurontin-gralise-horizant-gabapentin-and-lyrica-lyrica-cr-pregabalin-drug-safety-communication", type: "Government", desc: "FDA required new warnings about risk of respiratory depression with gabapentinoids, especially when combined with opioids. 49 cases reviewed, 12 deaths, 92% involved CNS depressant co-use. Source for gabapentin interaction ratings." },
    { name: "Henry & Hill — Fatal interaction between ritonavir and MDMA (Lancet, 1998)", url: "https://doi.org/10.1016/S0140-6736(05)79824-X", type: "Peer-reviewed", desc: "First documented fatal case of ritonavir potentiating MDMA. Post-mortem MDMA blood levels equivalent to 18-tablet overdose from a 2.5-tablet dose. Source for HIV antiretroviral interaction warnings." },
    { name: "Cohen et al. — Concomitant drugs and MDMA mortality (Scientific Reports, 2021)", url: "https://www.nature.com/articles/s41598-021-85389-x", type: "Peer-reviewed", desc: "FAERS database analysis finding bupropion has the highest odds ratio (2.82) for death when combined with MDMA of any antidepressant examined. Source for bupropion interaction rating." },
    { name: "Liverpool HIV Drug Interactions Checker", url: "https://www.hiv-druginteractions.org/checker", type: "Community", desc: "University of Liverpool's comprehensive drug interaction database for HIV medications, including recreational drug interactions. The gold standard reference for antiretroviral interaction data." },
  ]},
  { id: "addiction", label: "Addiction", sources: [
    { name: "Lopez-Quintero et al. — \"Probability and predictors of transition from first use to dependence\" (Drug and Alcohol Dependence, 2011)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3069146/", type: "Peer-reviewed", desc: "The primary source for our addiction data. Analyzed 43,093 participants from the NESARC study using survival analysis to estimate the probability of transitioning from first use to dependence for nicotine, alcohol, cannabis, and cocaine. Found that 67.5% of nicotine users, 22.7% of alcohol users, 20.9% of cocaine users, and 8.9% of cannabis users develop dependence at some point in their lives." },
    { name: "Anthony, Warner & Kessler — \"Comparative epidemiology of dependence\" (Experimental and Clinical Psychopharmacology, 1994)", url: "https://pubmed.ncbi.nlm.nih.gov/12404770/", type: "Peer-reviewed", desc: "The original landmark study on addiction capture rates from the National Comorbidity Survey (n=8,098). Established that 32% of tobacco users, 23% of heroin users, 17% of cocaine users, 15% of alcohol users, 9% of cannabis users, and ~4.9% of hallucinogen users develop dependence. Note: 'hallucinogens' includes PCP and possibly MDMA, not limited to classical psychedelics." },
    { name: "Stone et al. — \"Who is becoming hallucinogen dependent?\" (Drug and Alcohol Dependence, 2007)", url: "https://doi.org/10.1016/j.drugalcdep.2006.08.008", type: "Peer-reviewed", desc: "Using NHSDA 2000-2001 data (n=114,241), found 2-3% of recent-onset hallucinogen users developed dependence within 24 months under DSM-IV criteria. The best available incidence-window estimate for hallucinogen dependence." },
    { name: "Schlag — \"Percentages of problem drug use and their implications for policy making\" (Drug Science, Policy and Law, 2020)", url: "https://journals.sagepub.com/doi/10.1177/2050324520904540", type: "Peer-reviewed", desc: "Comprehensive review comparing addiction capture rates across studies, including both Anthony (1994) and SAMHSA (2016) data. Confirmed that the rank ordering of substance dependence rates has remained consistent across decades: nicotine > heroin > cocaine > alcohol > amphetamine > cannabis > psychedelics." },
  ]},
  { id: "safety", label: "Safety Margins", sources: [
    { name: "Gable — \"Comparison of acute lethal toxicity\" (Addiction, 2004) + American Scientist (2006)", url: "https://doi.org/10.1111/j.1360-0443.2004.00744.x", type: "Peer-reviewed", desc: "The definitive source for safety ratio data (lethal dose ÷ effective dose). The 2004 Addiction paper covers 20 substances including GHB (ratio 8), DXM (10), poppers (8), and caffeine (100). The 2006 American Scientist article adapted the same data. Cannabis, LSD, and psilocybin exceed 1,000:1." },
    { name: "Mittleman et al. — \"Triggering of myocardial infarction by cocaine\" (Circulation, 1999)", url: "https://doi.org/10.1161/01.cir.99.21.2737", type: "Peer-reviewed", desc: "Found a 23.7-fold increase in MI risk (95% CI: 8.5-66.3) during the 60 minutes after cocaine use. This is a relative risk, not absolute per-use incidence. Used for our cocaine cardiac risk data." },
    { name: "de la Torre et al. — \"MDMA pharmacokinetics\" (Clinical Pharmacokinetics, 2004)", url: "https://doi.org/10.2165/00003088-200443030-00001", type: "Peer-reviewed", desc: "MDMA is a mechanism-based inhibitor of CYP2D6 — it permanently inactivates the enzyme that metabolizes it. This means a second dose hits harder than the first because the body can't clear it as fast. Explains why redosing is disproportionately dangerous." },
    { name: "National Treatment Agency — Overdose Preventability Study (UK, 2007)", url: "https://www.drugsandalcohol.ie/6223/", type: "Government", desc: "Analysis of 151 overdose deaths in London. Informed our understanding of polydrug fatality patterns and tolerance-related overdose risk." },
  ]},
  { id: "supply", label: "Supply & Purity", sources: [
    { name: "DrugsData (formerly EcstasyData)", url: "https://drugsdata.org", type: "Lab analysis", desc: "Adulteration and purity data, especially for MDMA, is informed by DrugsData's 25+ year database of anonymously submitted drug samples analyzed by DEA-licensed laboratories. Their finding that only ~74% of 'MDMA' samples contain only MDMA (as of 2023) is referenced in our supply risk ratings." },
    { name: "DanceSafe", url: "https://dancesafe.org", type: "Nonprofit", desc: "The oldest drug checking kit manufacturer in the US. Their #TestIt alerts and on-site drug checking data inform our adulteration warnings. DanceSafe provides reagent test kits and fentanyl test strips.", link2: "https://dancesafe.org/drug-checking/", link2label: "Drug Checking Services" },
    { name: "DEA / NFLIS", url: "https://www.nflis.deadiversion.usdoj.gov/", type: "Government", desc: "Fentanyl co-occurrence rates in other drug supplies from forensic laboratory analysis of law enforcement seizures across the US. DEA CY2024 Annual Cocaine Report: levamisole now ~5% (down from 87% in 2017), average purity 88%." },
    { name: "Fentanyl Contamination Research (The Lancet, 2024)", url: "https://www.thelancet.com/journals/lanam/article/PIIS2667-193X(24)00225-4/fulltext", type: "Peer-reviewed", desc: "Found fentanyl co-occurs in over 10% of cocaine and methamphetamine samples in several Northeast US states. 2.7% nationally across 11.9 million NFLIS samples." },
    { name: "Frontiers in Psychiatry — Drug Checking in Recreational Settings (Italy, 2021)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7938318/", type: "Peer-reviewed", desc: "GC/MS-confirmed concordance rates: LSD 100%, cocaine 92%, amphetamine 91%, heroin 88%, MDMA 84%, ketamine 78%. One of the few studies with full laboratory confirmation of field drug checking results." },
    { name: "Maryland RAD (Rapid Analysis of Drugs) — Statewide Drug Checking 2021-2024", url: "https://www.sciencedirect.com/science/article/abs/pii/S0376871626000840", type: "Government", desc: "Only 22% of 792 samples were concordant with what buyers intended. Only 1.9% of samples intended as heroin tested positive for heroin. 57.3% contained xylazine. Demonstrates how dramatically the opioid supply has shifted." },
    { name: "Substance Drug Checking (UVic, Canada) — Monthly Reports 2023-2024", url: "https://substance.uvic.ca/blog/", type: "Lab analysis", desc: "One of the most transparent drug checking programs, publishing detailed monthly reports with substance-by-substance concordance rates. Tests thousands of samples per year from harm reduction sites across British Columbia using FTIR and DART-MS confirmation." },
    { name: "NZ Drug Foundation — Drug Checking Report 2024", url: "https://drugfoundation.org.nz/news-and-reports/report-drug-checking-2024", type: "Nonprofit", desc: "New Zealand's national drug checking program tested 3,200+ samples in 2024. Found 68% of drugs were what people expected, up from 64% in 2023. Detailed breakdowns by substance type." },
  ]},
  { id: "dosage", label: "Dosage & Effects", sources: [
    { name: "PsychonautWiki", url: "https://psychonautwiki.org", type: "Community", desc: "Dosage ranges, onset times, duration, and subjective effect profiles. One of the most detailed and regularly updated substance databases.", link2: "https://psychonautwiki.org/wiki/Dosage_classification", link2label: "Dosage Classification" },
    { name: "NHTSA — Drugs and Human Performance Fact Sheets", url: "https://www.nhtsa.gov/sites/nhtsa.gov/files/809725-drugshumanperformancefs.pdf", type: "Government", desc: "Detailed pharmacological profiles for 16 substances including dosage ranges, pharmacokinetics, metabolism, and drug interactions." },
    { name: "Erowid", url: "https://erowid.org", type: "Nonprofit", desc: "Effect descriptions, experience reports, and pharmacological reference data. The foundational online drug information resource since 1995.", link2: "https://erowid.org/experiences/", link2label: "Experience Vaults" },
    { name: "SAMHSA — National Survey on Drug Use and Health", url: "https://www.samhsa.gov/data/nsduh", type: "Government", desc: "Prevalence data and national trends in substance use. The most comprehensive annual survey of drug use in the United States." },
    { name: "Global Drug Survey (GDS) — Annual Reports 2019-2021 + Psychedelics Study 2020", url: "https://www.globaldrugsurvey.com/", type: "Community", desc: "The world's largest annual drug survey (85,000+ respondents in GDS2019). The GDS2020 psychedelics self-treatment study (n=3,364) found 22.5% of people self-treating with LSD or psilocybin reported negative psychological effects (note: combined both substances in a self-treatment context, not general recreational use).", link2: "https://www.globaldrugsurvey.com/wp-content/uploads/2021/01/GDS2020-Executive-Summary.pdf", link2label: "GDS 2020 Executive Summary" },
  ]},
];

const TYPE_COLORS = {
  "Peer-reviewed": { bg: "rgba(168,85,247,0.12)", c: "#a855f7" },
  "Government": { bg: "rgba(59,130,246,0.12)", c: "#60a5fa" },
  "Lab analysis": { bg: "rgba(6,182,212,0.12)", c: "#06b6d4" },
};
const DEFAULT_TYPE_COLOR = { bg: "rgba(34,197,94,0.12)", c: "#22c55e" };

export default function Sources() {
  const refs = useRef({});
  const setRef = useCallback((id) => (el) => { refs.current[id] = el; }, []);
  const scrollTo = (id) => {
    const el = refs.current[id];
    if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  return <div style={{ maxWidth: 760 }}>
    <h2 style={{ fontFamily: "'Instrument Serif',Georgia,serif", fontSize: 22, color: "#e8e6e3", fontWeight: 400, marginBottom: 4 }}>Data Sources</h2>
    <p style={{ fontSize: 13, color: "#8a8780", lineHeight: 1.6, marginBottom: 14 }}>DoseGuide cites primary sources wherever possible. Fields are annotated with confidence tiers: measured (direct from peer-reviewed data), derived (calculated from primary sources), estimated (informed approximation), or editorial (team judgment).</p>

    {/* Jump tabs */}
    <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 18, position: "sticky", top: 0, zIndex: 5, background: "#111113", padding: "8px 0 10px", borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
      {SECTIONS.map(s => <button key={s.id} onClick={() => scrollTo(s.id)} style={{ padding: "7px 12px", borderRadius: 7, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.03)", color: "#8a8780", fontFamily: "'DM Mono',monospace", fontSize: 12, cursor: "pointer", minHeight: 34 }}>{s.label}</button>)}
    </div>

    {SECTIONS.map(section => <div key={section.id} ref={setRef(section.id)} style={{ scrollMarginTop: 80, marginBottom: 24 }}>
      <h3 style={{ fontFamily: "'Instrument Serif',Georgia,serif", fontSize: 18, color: "#e8e6e3", fontWeight: 400, margin: "0 0 10px", paddingBottom: 6, borderBottom: "1px solid rgba(255,255,255,0.06)" }}>{section.label}</h3>
      {section.sources.map((src, i) => {
        const tc = TYPE_COLORS[src.type] || DEFAULT_TYPE_COLOR;
        return <div key={i} style={{ background: "rgba(255,255,255,0.02)", borderRadius: 10, border: "1px solid rgba(255,255,255,0.06)", padding: 16, marginBottom: 10 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 8, marginBottom: 6, flexWrap: "wrap" }}>
            <a href={src.url} target="_blank" rel="noopener noreferrer" style={{ fontFamily: "'Instrument Serif',Georgia,serif", fontSize: 17, color: "#e8e6e3", textDecoration: "none", borderBottom: "1px solid rgba(255,255,255,0.15)", fontWeight: 400 }}>{src.name}</a>
            <span style={{ fontSize: 12, padding: "4px 10px", borderRadius: 12, background: tc.bg, color: tc.c, fontFamily: "'DM Mono',monospace", flexShrink: 0 }}>{src.type}</span>
          </div>
          <p style={{ margin: "0 0 8px", fontSize: 13, color: "#8a8780", lineHeight: 1.6 }}>{src.desc}</p>
          <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
            <a href={src.url} target="_blank" rel="noopener noreferrer" style={{ fontSize: 13, color: "#6b9080", fontFamily: "'DM Mono',monospace", textDecoration: "none", padding: "4px 0", minHeight: 32, display: "inline-flex", alignItems: "center" }}>↗ Visit site</a>
            {src.link2 && <a href={src.link2} target="_blank" rel="noopener noreferrer" style={{ fontSize: 13, color: "#6b9080", fontFamily: "'DM Mono',monospace", textDecoration: "none", padding: "4px 0", minHeight: 32, display: "inline-flex", alignItems: "center" }}>↗ {src.link2label}</a>}
          </div>
        </div>;
      })}
    </div>)}

    <div style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 8, padding: 14, marginTop: 16 }}>
      <h3 style={{ margin: "0 0 6px", fontFamily: "'Instrument Serif',Georgia,serif", fontSize: 16, color: "#e8e6e3", fontWeight: 400 }}>Per-number sourcing</h3>
      <p style={{ margin: 0, fontSize: 12.5, color: "#a09d97", lineHeight: 1.6 }}>Every quantitative claim on this site — harm scores, addiction rates, safety margins, purity percentages — has a per-field citation in the source code. Each number is tagged with its source study, a confidence level (<span style={{ fontFamily: "'DM Mono',monospace", color: "#4ade80" }}>measured</span>, <span style={{ fontFamily: "'DM Mono',monospace", color: "#60a5fa" }}>derived</span>, <span style={{ fontFamily: "'DM Mono',monospace", color: "#f59e0b" }}>estimated</span>, or <span style={{ fontFamily: "'DM Mono',monospace", color: "#f97316" }}>editorial</span>), and a note explaining how the number was obtained. Tap the <span style={{ fontFamily: "'DM Mono',monospace", background: "rgba(255,255,255,0.06)", padding: "2px 6px", borderRadius: 4 }}>?</span> buttons in the Rankings charts to see sourcing for individual numbers.</p>
    </div>
    <div style={{ background: "rgba(245,158,11,0.06)", border: "1px solid rgba(245,158,11,0.15)", borderRadius: 8, padding: 14, marginTop: 10 }}>
      <h3 style={{ margin: "0 0 6px", fontFamily: "'Instrument Serif',Georgia,serif", fontSize: 16, color: "#c4a050", fontWeight: 400 }}>A note on data quality</h3>
      <p style={{ margin: 0, fontSize: 12.5, color: "#a09070", lineHeight: 1.6 }}>No single source is perfect. We cross-reference multiple sources and err on the side of caution — when sources disagree, we use the more conservative estimate. If you find an error, please <a href="https://github.com/cdepman/doseguide.org/issues" target="_blank" rel="noopener noreferrer" style={{ color: "#c4a050", textDecoration: "none", borderBottom: "1px solid rgba(196,160,80,0.3)" }}>open an issue on GitHub</a>.</p>
    </div>
  </div>;
}
