const SOURCES = [
  { name: "TripSit", url: "https://tripsit.me", type: "Community", desc: "The drug combination chart and interaction data used in the Combination Checker and Matrix are derived from TripSit's research. Their combo chart (v4.0) is the most comprehensive publicly available drug interaction reference, maintained by volunteers and reviewed by pharmacologists.", link2: "https://wiki.tripsit.me/wiki/Drug_combinations", link2label: "Drug Combinations Wiki" },
  { name: "Nutt, King & Phillips — \"Drug harms in the UK\" (The Lancet, 2010)", url: "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(10)61462-6/fulltext", type: "Peer-reviewed", desc: "The harm scores for 14 substances come directly from this landmark multicriteria decision analysis, in which an expert panel scored 20 substances on 16 criteria covering harm to users and harm to others. Scores for substances not in the original study (fentanyl, tramadol, kratom, DXM, nitrous, 2C-x, poppers, DMT, mescaline, PCP, caffeine) are DoseGuide estimates based on clinical literature and are marked with dashed bars in the charts. Note: nicotine is scored as 'tobacco' (26) in the original study — this includes all smoking-related harms, not nicotine alone." },
  { name: "DrugsData (formerly EcstasyData)", url: "https://drugsdata.org", type: "Lab analysis", desc: "Adulteration and purity data, especially for MDMA, is informed by DrugsData's 25+ year database of anonymously submitted drug samples analyzed by DEA-licensed laboratories. Their finding that only ~74% of 'MDMA' samples contain only MDMA (as of 2023) is referenced in our supply risk ratings." },
  { name: "DanceSafe", url: "https://dancesafe.org", type: "Nonprofit", desc: "The oldest drug checking kit manufacturer in the US. Their #TestIt alerts and on-site drug checking data inform our adulteration warnings. DanceSafe provides reagent test kits and fentanyl test strips.", link2: "https://dancesafe.org/drug-checking/", link2label: "Drug Checking Services" },
  { name: "NHTSA — Drugs and Human Performance Fact Sheets", url: "https://www.nhtsa.gov/sites/nhtsa.gov/files/809725-drugshumanperformancefs.pdf", type: "Government", desc: "Detailed pharmacological profiles for 16 substances including dosage ranges, pharmacokinetics, metabolism, and drug interactions." },
  { name: "PsychonautWiki", url: "https://psychonautwiki.org", type: "Community", desc: "Dosage ranges, onset times, duration, and subjective effect profiles. One of the most detailed and regularly updated substance databases.", link2: "https://psychonautwiki.org/wiki/Dosage_classification", link2label: "Dosage Classification" },
  { name: "Erowid", url: "https://erowid.org", type: "Nonprofit", desc: "Effect descriptions, experience reports, and pharmacological reference data. The foundational online drug information resource since 1995.", link2: "https://erowid.org/experiences/", link2label: "Experience Vaults" },
  { name: "Gable — \"The Toxicity of Recreational Drugs\" (American Scientist, 2006)", url: "https://www.americanscientist.org/article/the-toxicity-of-recreational-drugs", type: "Peer-reviewed", desc: "The safety margin data — the ratio of a lethal dose to an effective dose — showing cannabis, LSD, and psilocybin have ratios exceeding 1,000:1." },
  { name: "National Treatment Agency — Overdose Preventability Study (UK, 2007)", url: "https://www.drugsandalcohol.ie/6223/", type: "Government", desc: "Analysis of 151 overdose deaths in London. Informed our understanding of polydrug fatality patterns and tolerance-related overdose risk." },
  { name: "SAMHSA — National Survey on Drug Use and Health", url: "https://www.samhsa.gov/data/nsduh", type: "Government", desc: "Prevalence data and national trends in substance use. The most comprehensive annual survey of drug use in the United States." },
  { name: "DEA / NFLIS", url: "https://www.nflis.deadiversion.usdoj.gov/", type: "Government", desc: "Fentanyl co-occurrence rates in other drug supplies from forensic laboratory analysis of law enforcement seizures across the US." },
  { name: "Fentanyl Contamination Research (The Lancet, 2024)", url: "https://www.thelancet.com/journals/lanam/article/PIIS2667-193X(24)00225-4/fulltext", type: "Peer-reviewed", desc: "Found fentanyl co-occurs in over 10% of cocaine and methamphetamine samples in several Northeast US states." },
  { name: "Lopez-Quintero et al. — \"Probability and predictors of transition from first use to dependence\" (Drug and Alcohol Dependence, 2011)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3069146/", type: "Peer-reviewed", desc: "The primary source for our addiction data. Analyzed 43,093 participants from the NESARC study using survival analysis to estimate the probability of transitioning from first use to dependence for nicotine, alcohol, cannabis, and cocaine. Found that 67.5% of nicotine users, 22.7% of alcohol users, 20.9% of cocaine users, and 8.9% of cannabis users develop dependence at some point in their lives." },
  { name: "Schlag — \"Percentages of problem drug use and their implications for policy making\" (Drug Science, Policy and Law, 2020)", url: "https://journals.sagepub.com/doi/10.1177/2050324520904540", type: "Peer-reviewed", desc: "Comprehensive review comparing addiction capture rates across studies, including both Anthony (1994) and SAMHSA (2016) data. Confirmed that the rank ordering of substance dependence rates has remained consistent across decades: nicotine > heroin > cocaine > alcohol > amphetamine > cannabis > psychedelics." },
  { name: "Anthony, Warner & Kessler — \"Comparative epidemiology of dependence\" (Experimental and Clinical Psychopharmacology, 1994)", url: "https://pubmed.ncbi.nlm.nih.gov/12404770/", type: "Peer-reviewed", desc: "The original landmark study on addiction capture rates from the National Comorbidity Survey (n=8,098). Established that 32% of tobacco users, 23% of heroin users, 17% of cocaine users, 15% of alcohol users, and 9% of cannabis users develop dependence. Referenced for substances not covered by Lopez-Quintero." },
  { name: "Substance Drug Checking (UVic, Canada) — Monthly Reports 2023-2024", url: "https://substance.uvic.ca/blog/", type: "Lab analysis", desc: "One of the most transparent drug checking programs, publishing detailed monthly reports with substance-by-substance concordance rates. Tests thousands of samples per year from harm reduction sites across British Columbia using FTIR and DART-MS confirmation." },
  { name: "NZ Drug Foundation — Drug Checking Report 2024", url: "https://drugfoundation.org.nz/news-and-reports/report-drug-checking-2024", type: "Nonprofit", desc: "New Zealand's national drug checking program tested 3,200+ samples in 2024. Found 68% of drugs were what people expected, up from 64% in 2023. Detailed breakdowns by substance type." },
  { name: "Frontiers in Psychiatry — Drug Checking in Recreational Settings (Italy, 2021)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7938318/", type: "Peer-reviewed", desc: "GC/MS-confirmed concordance rates: LSD 100%, cocaine 92%, amphetamine 91%, heroin 88%, MDMA 84%, ketamine 78%. One of the few studies with full laboratory confirmation of field drug checking results." },
  { name: "Maryland RAD (Rapid Analysis of Drugs) — Statewide Drug Checking 2021-2024", url: "https://www.sciencedirect.com/science/article/abs/pii/S0376871626000840", type: "Government", desc: "Only 22% of 792 samples were concordant with what buyers intended. Only 1.9% of samples intended as heroin tested positive for heroin. 57.3% contained xylazine. Demonstrates how dramatically the opioid supply has shifted." },
  { name: "Global Drug Survey (GDS) — Annual Reports 2019-2021 + Psychedelics Study 2020", url: "https://www.globaldrugsurvey.com/", type: "Community", desc: "The world's largest annual drug survey (85,000+ respondents in GDS2019). Tracks rates of seeking emergency medical treatment by substance, psychological adverse effects, and dosing practices. The GDS2020 psychedelics self-treatment study (n=3,364) found 22.5% of people self-treating with LSD or psilocybin reported negative psychological effects (note: this combined both substances in a self-treatment context, not general recreational use).", link2: "https://www.globaldrugsurvey.com/wp-content/uploads/2021/01/GDS2020-Executive-Summary.pdf", link2label: "GDS 2020 Executive Summary" },
];

const TYPE_COLORS = {
  "Peer-reviewed": { bg: "rgba(168,85,247,0.12)", c: "#a855f7" },
  "Government": { bg: "rgba(59,130,246,0.12)", c: "#60a5fa" },
  "Lab analysis": { bg: "rgba(6,182,212,0.12)", c: "#06b6d4" },
};
const DEFAULT_TYPE_COLOR = { bg: "rgba(34,197,94,0.12)", c: "#22c55e" };

export default function Sources() {
  return <div style={{ maxWidth: 760 }}>
    <h2 style={{ fontFamily: "'Instrument Serif',Georgia,serif", fontSize: 22, color: "#e8e6e3", fontWeight: 400, marginBottom: 4 }}>Data Sources</h2>
    <p style={{ fontSize: 13, color: "#8a8780", lineHeight: 1.6, marginBottom: 20 }}>DoseGuide synthesizes data from peer-reviewed research, government agencies, and community harm reduction organizations. Every piece of data in this tool can be traced to one or more of these sources.</p>
    {SOURCES.map((src, i) => {
      const tc = TYPE_COLORS[src.type] || DEFAULT_TYPE_COLOR;
      return <div key={i} style={{ background: "rgba(255,255,255,0.02)", borderRadius: 10, border: "1px solid rgba(255,255,255,0.06)", padding: 16, marginBottom: 10 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 8, marginBottom: 6, flexWrap: "wrap" }}>
          <a href={src.url} target="_blank" rel="noopener noreferrer" style={{ fontFamily: "'Instrument Serif',Georgia,serif", fontSize: 17, color: "#e8e6e3", textDecoration: "none", borderBottom: "1px solid rgba(255,255,255,0.15)", fontWeight: 400 }}>{src.name}</a>
          <span style={{ fontSize: 12, padding: "4px 10px", borderRadius: 12, background: tc.bg, color: tc.c, fontFamily: "'DM Mono',monospace", flexShrink: 0 }}>{src.type}</span>
        </div>
        <p style={{ margin: "0 0 8px", fontSize: 13, color: "#8a8780", lineHeight: 1.6 }}>{src.desc}</p>
        <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
          <a href={src.url} target="_blank" rel="noopener noreferrer" style={{ fontSize: 13, color: "#6b9080", fontFamily: "'DM Mono',monospace", textDecoration: "none", padding: "4px 0", minHeight: 32, display: "inline-flex", alignItems: "center" }}>↗ Visit site</a>
          {src.link2 && <a href={src.link2} target="_blank" rel="noopener noreferrer" style={{ fontSize: 13, color: "#6b9080", fontFamily: "'DM Mono',monospace", textDecoration: "none", padding: "4px 0", minHeight: 32, display: "inline-flex", alignItems: "center" }}>↗ {src.link2label}</a>}
        </div>
      </div>;
    })}
    <div style={{ background: "rgba(245,158,11,0.06)", border: "1px solid rgba(245,158,11,0.15)", borderRadius: 8, padding: 14, marginTop: 16 }}>
      <h3 style={{ margin: "0 0 6px", fontFamily: "'Instrument Serif',Georgia,serif", fontSize: 16, color: "#c4a050", fontWeight: 400 }}>A note on data quality</h3>
      <p style={{ margin: 0, fontSize: 12.5, color: "#a09070", lineHeight: 1.6 }}>No single source is perfect. We cross-reference multiple sources and err on the side of caution — when sources disagree, we use the more conservative estimate. If you find an error, please let us know.</p>
    </div>
  </div>;
}
